# permissions for end users to edit dnsendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsendpoint-editor-role
rules:
- apiGroups:
  - k8s.admitriev.eu
  resources:
  - dnsendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.admitriev.eu
  resources:
  - dnsendpoints/status
  verbs:
  - get
