# permissions for end users to view dnsendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsendpoint-viewer-role
rules:
- apiGroups:
  - k8s.admitriev.eu
  resources:
  - dnsendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.admitriev.eu
  resources:
  - dnsendpoints/status
  verbs:
  - get
